# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment:
      name: cotton-pavilion
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    # 镜像推送到 阿里云仓库
    - name: Login to the Ali Registry
      uses: docker/login-action@v3.0.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIHUB_USERNAME }}
        password: ${{ secrets.ALIHUB_PASSWORD }}

    - name: Build and push to Ali
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: |
          registry.cn-hangzhou.aliyuncs.com/entangledcotton/cotton-pavilion:latest
